imports:
    - { resource: parameters.yml }
    - { resource: services/event_listeners.yml }
    - { resource: services/security.yml }
    # - { resource: services/data_collector.yml }

services:
    gordalina_mixpanel.registry:
        class: "%gordalina_mixpanel.registry.class%"

    gordalina_mixpanel.flusher:
        class: "%gordalina_mixpanel.flusher.class%"
        arguments:
            - "@gordalina_mixpanel.registry"
            - "@?debug.stopwatch"
            - "%gordalina_mixpanel.enable_profiler%"
        lazy: true
        public: false

    gordalina_mixpanel.expression_language:
        class: "%gordalina_mixpanel.expression_language.class%"
        lazy: true
        public: false
